version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: academia_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - default
      # No exponemos puerto 5432 al público por seguridad

  auth-service:
    build: ./backend/auth-service
    container_name: academia_auth
    restart: always
    environment:
      - PORT=3001
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=academia_auth
    depends_on:
      - postgres
    networks:
      - default
      - web # Conexión al Proxy

  courses-service:
    build: ./backend/courses-service
    container_name: academia_courses
    restart: always
    environment:
      - PORT=3002
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=academia_courses
    depends_on:
      - postgres
    networks:
      - default
      - web # Conexión al Proxy

  frontend:
    build:
      context: ./frontend
      # El frontend apunta al dominio público del Auth Service
      args:
        VITE_API_URL: "http://auth.149.50.130.160.nip.io"
    container_name: academia_frontend
    restart: always
    networks:
      - default
      - web # Conexión al Proxy

networks:
  web:
    external: true

volumes:
  postgres_data:
