version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: academia_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - academia_net

  auth-service:
    build: ./backend/auth-service
    container_name: academia_auth
    restart: always
    environment:
      - PORT=3001
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=academia_auth
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    networks:
      - academia_net

  courses-service:
    build: ./backend/courses-service
    container_name: academia_courses
    restart: always
    environment:
      - PORT=3002
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=academia_courses
    depends_on:
      - postgres
    ports:
      - "3002:3002"
    networks:
      - academia_net

  frontend:
    build:
      context: ./frontend
      args:
        # Aquí definimos la IP pública de tu servidor para que React sepa dónde pedir datos
        - VITE_API_URL=http://149.50.130.160:3001
    container_name: academia_frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - academia_net

networks:
  academia_net:
    driver: bridge

volumes:
  postgres_data:
